### PR TITLE
Checkout repo and run pytest

### PR DESCRIPTION
**Pull request by caspervdw**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This is a different approach from  #25 to run pytest here.

### CODE REVIEW

**Comment by caspervdw** [comment]
This works, only `from sys import getrefcount` does not work on pypy as `sys.getrefcount` is not implemented on pypy.

We should skip these tests on pypy.

**Comment by caspervdw** [comment]
I’d like to have this merged at some point @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
This could be easier now with the tests included in the package?

**Comment by caspervdw** [comment]
Absolutely. This PR is outdated now.

**Pull request closed without merging**
