### PR TITLE
Bump to 0.10.2 and enable tests

### PR DESCRIPTION
**Pull request by caspervdw**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by caspervdw** [comment]
@conda-forge-admin, please rerender

**Comment by jorisvandenbossche** [comment]
Changes look good. I don't know why, but CI doesn't seem to be running (only the linter ran)

**Comment by caspervdw** [comment]
@conda-forge-admin, please restart ci

**Comment by caspervdw** [comment]
Related issue: https://github.com/conda-forge/status/issues/117

There is actually something running, it just isn't shown as a check:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=366760&view=results

**Comment by caspervdw** [comment]
Everything is passing, also Pypy, which is a first :tada:

**Comment by jorisvandenbossche** [comment]
Nice! :)

**Pull request merged**
