### PR TITLE
Remove custom build config for GEOS versions

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@jorisvandenbossche I bumped the build number to avoid creating packages with different hash but similar functionalities. Those are one of the culprits on making conda's solver slow. Mamba will always prefer the higher build number and making the solution faster.

**Comment by jorisvandenbossche** [comment]
For my understanding, if this PR was merged without increasing the build number, would it actually upload new packages to anaconda.org? Because in principle this wouldn't be needed in this case, since this doesn't add any new functionality or dependency build version (and I assumed that not increasing the build number would then not upload anything)

**Comment by ocefpaf** [comment]
> For my understanding, if this PR was merged without increasing the build number, would it actually upload new packages to anaconda.org? Because in principle this wouldn't be needed in this case, since this doesn't add any new functionality or dependency build version (and I assumed that not increasing the build number would then not upload anything)

It should not and your line of though is correct. But sometimes the build changes the hash and we get a "new" package that is the same as the old package.

**Pull request merged**
